# Generated by Django 5.1.1 on 2024-12-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_networthmodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('otp', models.CharField(max_length=8)),
                ('expirytime', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='NetworthModel',
        ),
    ]
