# Generated by Django 5.1.1 on 2024-12-18 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_otpmodel_delete_networthmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPModel',
        ),
    ]
